### ISSUE TITLE
AWS GovCloud regions not supported

### ISSUE THREAD

**Issue by jamessevener** [mtougeron/k8s-pvc-tagger#101]
**Describe the bug**
AWS GovCloud regions to not match expected region

**To Reproduce**
1. Deploy k8s-pvc-tagger to AWS GovCloud hosted k8s cluster

**Expected behavior**
GovCloud regions are supported, and pods don't crash

**Additional context**
"level":"debug","msg":"ec2Metadata region","region":"us-gov-west-1"
"level":"fatal","msg":"Given AWS_REGION does not match AWS Region format."

https://github.com/mtougeron/k8s-pvc-tagger/blob/66cc9e12413e892800b6e291cd52ee18a726260b/aws.go#L43
Regex doesn't match for gov regions

**Comment by headkm** [comment]
A workable regex for this would be something like 
`^[\w]{2}[-][\w]{4,9}[-][\d]$|^[\w]{2}[-][\w]{3}[-][\w]{4,9}[-][\d]$`
