### ISSUE TITLE
Tag EFS access Points in aws for PVC created using EFS storage class

### ISSUE THREAD

**Issue by wadhwakabir** [mtougeron/k8s-pvc-tagger#50]
**Is your feature request related to a problem? Please describe.**
Tool currently tags PVC that are created in aws using EBS storage class, needed functionality to tag PVC created using EFS storage class.

**Describe the solution you'd like**
Using existing Informer that is watching all PVC, add condition for efs, and fetch efs access point details from persistent volume and tag particular access point using same annotation logic.

**Describe alternatives you've considered**
remove repo to k8s-aws-pvc tagger for generic use

**Additional context**
I have made changes in my fork project

**Comment by mtougeron** [comment]
I'm open to this idea. Since you've made the changes in your forked version would you be willing to create a PR with them?

**Comment by wadhwakabir2** [comment]
raised PR for same https://github.com/mtougeron/k8s-aws-ebs-tagger/pull/51

**Comment by wadhwakabir** [comment]
https://github.com/mtougeron/k8s-aws-ebs-tagger/pull/55

**Comment by mtougeron** [comment]
This has been completed and merged with #55
