### ISSUE TITLE
Tag existing AWS resources

### ISSUE THREAD

**Issue by Lorderot** [mtougeron/k8s-pvc-tagger#69]
**Problem description**
Whenever k8s-pvc-tagger is deployed there might be already many untagged PVCs (and dynamically provisioned PVs / EBS / EFS).

**Solution**
If a flag (e.g. `tag-existing-resources`) is set, the tagger lists all the PVCs and tries to tag the underlying EBS/EFS.

**Comment by mtougeron** [comment]
I'm not sure I'm following the behavior you're expecting here. It won't tag any PVCs without the expected tags so there is no work to be done when the app first starts. If you are starting to use it for the first time, deploy the k8s-pvc-tagger first, then start to annotate the PVC(s), it will then tag the underlying EBS/EFS volumes as the modifications to the PVC(s) are made.

**Comment by Lorderot** [comment]
Sorry, you are right; i just tested it in minikube quickly and made some mistakes. Moreover, if the PVCs are tagged, after the deployment the tagger will receive "add" event from the informer for every PVC (so if they are tagged correctly, they will be processed)
