### ISSUE TITLE
Parsing AWS volumeID is failing

### ISSUE THREAD

**Issue by gkoufoud** [mtougeron/k8s-pvc-tagger#74]
**Describe the bug**
When creating a new EBS volume (EKS v1.23) using the intree provisioner, the request is redirected to te csi driver which creates the PV object with volumeID: vol-xxxxxx without the aws:// prefix. This is expected according to [this](https://github.com/kubernetes/csi-translation-lib/blob/master/plugins/aws_ebs.go#L231-L237). Though the k8s-pvc-tagger fails to parse the PV object since the [regex ](https://github.com/mtougeron/k8s-pvc-tagger/blob/main/kubernetes.go#L53) doesn't include that case.
I think that the regex can be changed to something like: `^(?:aws:\/\/\w{2}-\w{4,9}-\d\w\/){0,1}(vol-\w+){1}$`
**To Reproduce**
1. Create a new PVC using the intree provisioner
2. Watch the k8s-pvc-tagger logs

**Expected behavior**
k8s-pvc-tagger should be able to tag the ebs volume.

**Comment by mtougeron** [comment]
Thanks for the report. I've patched the relevant code and I'm publishing a new version of the application now. The Helm chart will come later today.
